version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgres
    restart: always
    environment:
      - POSTGRES_DATABASE=db_e_learning
      - POSTGRES_USER=mouny@mouny-db
      - POSTGRES_PASSWORD=admin_part_1
    ports:
      - 5432:5234
  app:
    restart: always
    build: .
    image: e_learning_postgres
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app

volumes:
  db_data: {}
