version: "3.9"
services:
  app:
    restart: always
    build: .
    image: e_learning_postgres
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
